### ISSUE TITLE
Add broker name to jvm metrics

### ISSUE THREAD

**Issue by naude-r** [rh-messaging/artemis-prometheus-metrics-plugin#16]
currently the jvm metrics do not include the broker name. this is causing an issue when creating dashboards as the instance tag added by prometheus may not align with the broker name.

this might be as simple as:
`meterRegistry.config().commonTags("broker", "XXXX");`

not sure how to query the current server instance to get to the broker....

**Comment by brusdev** [comment]
@naude-r this seems more an issue for the Apache ActiveMQ Artemis [MetricsManager](https://github.com/apache/activemq-artemis/blob/2.28.0/artemis-server/src/main/java/org/apache/activemq/artemis/core/server/metrics/MetricsManager.java).

**Comment by naude-r** [comment]
@brusdev thank you, you are right. will log an issue with the artemis team.

**Comment by naude-r** [comment]
[ARTEMIS-4291](https://issues.apache.org/jira/browse/ARTEMIS-4291) logged

**Comment by brusdev** [comment]
@naude-r are you planning to create a PR to fix [ARTEMIS-4291](https://issues.apache.org/jira/browse/ARTEMIS-4291)?

**Comment by naude-r** [comment]
@brusdev yes, that is the plan.

**Comment by naude-r** [comment]
PR [4487](https://github.com/apache/activemq-artemis/pull/4487) submitted.

a new method, bind, was added to ActiveMQMetricsPlugin (default empty implementation). this was needed to make the order more explicit.

**Comment by naude-r** [comment]
[ARTEMIS-4291](https://issues.apache.org/jira/browse/ARTEMIS-4291) merged for next release.

part of the above discussion resulted in additional metrics being added as well:
[ARTEMIS-4292](https://issues.apache.org/jira/browse/ARTEMIS-4292) merged and available.

**Comment by brusdev** [comment]
@naude-r great work!!!

**Comment by gauravtayade11** [comment]
@brusdev not getting jar and war file in repo

**Comment by brusdev** [comment]
@gauravtayade11 this repository is supported by Red Hat, you can download the artifacts from the Red Hat public maven repository, i.e.
https://maven.repository.redhat.com/ga/com/redhat/amq-broker/artemis-prometheus-metrics-plugin/2.0.0.redhat-00002/artemis-prometheus-metrics-plugin-2.0.0.redhat-00002.jar
https://maven.repository.redhat.com/ga/com/redhat/amq-broker/artemis-prometheus-metrics-plugin-servlet/2.0.0.redhat-00002/artemis-prometheus-metrics-plugin-servlet-2.0.0.redhat-00002.war
