### ISSUE TITLE
Getting started tutorial

### ISSUE THREAD

**Issue by jesperpedersen** [rh-messaging/artemis-prometheus-metrics-plugin#23]
If you get the components installed, then what ?

What is the endpoint ?

What are the supported metrics ?

**Comment by brusdev** [comment]
@jesperpedersen you can find the documentation at https://access.redhat.com/documentation/en-us/red_hat_amq_broker/7.11/html/managing_amq_broker/assembly-br-monitoring-broker-runtime-metrics_managing

**Comment by jesperpedersen** [comment]
Can this be in the repo ?

**Comment by brusdev** [comment]
@jesperpedersen
