### ISSUE TITLE
Possible race when servlet discovers registry?

### ISSUE THREAD

**Issue by jbertram** [rh-messaging/artemis-prometheus-metrics-plugin#25]
This report comes from ASF Slack:

> Hi, I've enabled Artemis Prometheus metrics as follow in my `broker.xml`:
> ```xml
> <metrics>
>   <plugin class-name="org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin"/>
> </metrics>
> ```
> It works most of the time and I'm able to get Prometheus metrics. However, randomly (usually after node restart) some nodes don't have metrics anymore and display the following error:
> ```
> HTTP ERROR 404 Prometheus meter registry is null. Has the Prometheus Metrics Pluging been configured?
> ```
> There is no visible difference in logs produced by a node having metrics and a node having no metrics. I don't know how to reproduce it. As a workaround, I have found that metrics can be enabled again by calling the JMX `restartEmbeddedWebServer()` to restart the Jetty server. Have you already seen something like that?

**Comment by brusdev** [comment]
Resolved by https://github.com/rh-messaging/artemis-prometheus-metrics-plugin/commit/1e0166fc9b2977e067d310dcbc0e6491eb452fba
