### ISSUE TITLE
Publish binaries 3.0.0

### ISSUE THREAD

**Issue by razvan-strimbulescu-fnt** [rh-messaging/artemis-prometheus-metrics-plugin#27]
Hello,

Any plans to publish the artifact 3.0.0?

I've look on the link below, but I saw only 2.0.0, 2.1.0
https://maven.repository.redhat.com/ga/com/redhat/amq-broker/

Thanks

**Comment by brusdev** [comment]
@razvan-strimbulescu-fnt the artifact 3.0.0 will be published at the end of April the Red Hat maven repository

**Comment by erilor** [comment]
Hi,

It seems the binaries still aren't published (or at least not at that location). 

There's also 3.1.0 published here on Github. What is the plan going forward? Will the binaries be published here or on maven.repository.redhat.com (or both)?

**Comment by brusdev** [comment]
We changed our plan: the artifact 3.0.0 wont be published. Only the artifact 3.2.0 will be published in the next weeks on maven.repository.redhat.com and the artifact 3.1.0 will be removed.
