### ISSUE TITLE
3.0.0 WebApp Error

### ISSUE THREAD

**Issue by evannorstrand-mp** [rh-messaging/artemis-prometheus-metrics-plugin#29]
I am trying to deploy the latest 3.0.0 release. I built it using java 11, and it's failing on startup.

2024-04-01 19:39:33,265 WARN  [org.eclipse.jetty.webapp.WebAppContext] Failed startup of context o.e.j.w.WebAppContext@16f0ec18{/metrics,file:///var/lib/artemis-instance/tmp/webapps/metrics.war/webapp/,UNAVAILABLE,@Connector-0}{/var/lib/artemis-instance/web/metrics.war}
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    | java.lang.NoClassDefFoundError: jakarta/servlet/http/HttpServlet
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.net.URLClassLoader.defineClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.net.URLClassLoader$1.run(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.net.URLClassLoader$1.run(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.webapp.WebAppClassLoader.foundClass(WebAppClassLoader.java:594) ~[jetty-webapp-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.webapp.WebAppClassLoader.loadAsResource(WebAppClassLoader.java:567) ~[jetty-webapp-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:502) ~[jetty-webapp-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.Loader.loadClass(Loader.java:59) ~[jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:97) ~[jetty-servlet-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:369) ~[jetty-servlet-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$2(ServletHandler.java:724) ~[jetty-servlet-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:749) ~[jetty-servlet-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392) ~[jetty-servlet-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304) ~[jetty-webapp-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:901) ~[jetty-server-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) ~[jetty-servlet-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532) [jetty-webapp-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) [jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) [jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) [jetty-server-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) [jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.server.Server.start(Server.java:470) [jetty-server-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) [jetty-server-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.server.Server.doStart(Server.java:415) [jetty-server-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.apache.activemq.artemis.component.WebServerComponent.start(WebServerComponent.java:215) [artemis-web-2.33.0.jar:2.33.0]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.addExternalComponent(ActiveMQServerImpl.java:1018) [artemis-server-2.33.0.jar:2.33.0]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:145) [artemis-cli-2.33.0.jar:2.33.0]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:221) [artemis-cli-2.33.0.jar:2.33.0]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:167) [artemis-cli-2.33.0.jar:2.33.0]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:157) [artemis-boot.jar:2.33.0]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:64) [artemis-boot.jar:2.33.0]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    | Caused by: java.lang.ClassNotFoundException: jakarta.servlet.http.HttpServlet
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:511) ~[jetty-webapp-10.0.20.jar:10.0.20]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
artemis-1_artemis-primary.1.qjlk96i4wfil@ip-10-104-8-173    |   ... 49 more

**Comment by Jean-Emile** [comment]
Implemented a 'potential' solution to the reported issue and pushed a draft to the following pull request: https://github.com/rh-messaging/artemis-prometheus-metrics-plugin/pull/30.

**Comment by brusdev** [comment]
@Jean-Emile artemis-prometheus-metrics-plugin 3.x was intentionally updated to jakarta.servlet. You can use artemis-prometheus-metrics-plugin 2.x for ActiveMQArtemis versions that require javax.servlet.

**Comment by evannorstrand-mp** [comment]
@brusdev - I am using the latest release, 2.33.0 and version 3 of this plugin does not work. What version of artemis should I be using with v3?

**Comment by brusdev** [comment]
@Jean-Emile artemis-prometheus-metrics-plugin 3.x is for future ActiveMQArtemis versions. You can use artemis-prometheus-metrics-plugin 2.1.0 for ActiveMQArtemis 2.33.0.

**Comment by svanschalkwyk** [comment]
Fantastic! Doesn't build on JDK17, but builds on JDK11.
