### ISSUE TITLE
Metrics for queues

### ISSUE THREAD

**Issue by padapl** [rh-messaging/artemis-prometheus-metrics-plugin#4]
Hello,

Is there any way to enable/disable metrics on queue level?

I have made some experiments with address-settings.xml. It seems to work on <address> level only:

	_<address-setting match="someTopic">
		<enable-metrics>true</enable-metrics>
	</address-setting>_

It does not work for:

	_<address-setting match="someQueue1">
		<enable-metrics>true</enable-metrics>
	</address-setting>_

My Artemis EB implementation has structure:

    _<address name="someTopic">
        <multicast>
            <queue name="someQueue1"/>
            <queue name="someQueue2"/>
            <queue name="someQueue3"/>
        </multicast>
    </address>_

Regards,
Pawel

**Comment by brusdev** [comment]
The ArtemisPrometheusMetricsPlugin just exposes metrics implemented by ActiveMQ Artemis.

You could send an email to users@activemq.apache.org to get more info
