### ISSUE TITLE
broker.xml: tag changed from metrics-plugin to metrics/plugin

### ISSUE THREAD

**Issue by 2019-05-10** [rh-messaging/artemis-prometheus-metrics-plugin#7]
With Artemis 2.18.0 the tag
```
<metrics-plugin class-name="org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin"/>
```

changed to

```
<metrics>
  <plugin class-name="org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin"/>
</metrics>
```

**Comment by brusdev** [comment]
The `metrics-plugin` element has been deprecated in favor of the `metrics` element since 2.14 but it is still usable for backward compatibility.

**Comment by 2019-05-10** [comment]
No doubt, but 2.14 is almost one and half a year old, and current is 2.19.0.
So, as documentation goes, shouldn't it target installation in a fairly recent version?

**Comment by brusdev** [comment]
I'm not sure to get the point, the latest documentation points to the new element: `metrics-plugin`
https://activemq.apache.org/components/artemis/documentation/latest/metrics.html#configuration

**Comment by brusdev** [comment]
Maybe you was talking about the [README.md](https://github.com/rh-messaging/artemis-prometheus-metrics-plugin/blob/master/README.md) of this repository.

In this case feel free to send a PR to update it, I'll merge it.

**Comment by brusdev** [comment]
README updated
