### ISSUE TITLE
Publish binaries 

### ISSUE THREAD

**Issue by attiand** [rh-messaging/artemis-prometheus-metrics-plugin#9]
Any plans to publish pre-built Maven artifacts for this project? 

I could provide a PR, but I would have to change the Maven coordinates to point at the github repo without any involvement from others.

**Comment by brusdev** [comment]
The maven artifacts are built and published by RedHat at https://maven.repository.redhat.com/ga/

https://maven.repository.redhat.com/ga/org/apache/activemq/artemis-prometheus-metrics-pom/
https://maven.repository.redhat.com/ga/org/apache/activemq/artemis-prometheus-metrics-plugin/
https://maven.repository.redhat.com/ga/org/apache/activemq/artemis-prometheus-metrics-plugin-servlet/

**Comment by attiand** [comment]
Sweet! :+1:

**Comment by mrjoops** [comment]
Hi @brusdev!

Do you know why versions 2+ aren't published there anymore ?

**Comment by brusdev** [comment]
Hi @mrjoops, the maven artifacts 2+ use the new group `com.redhat.amq-broker` they are built and published by RedHat at https://maven.repository.redhat.com/ga/

https://maven.repository.redhat.com/ga/com/redhat/amq-broker/artemis-prometheus-metrics-pom/
https://maven.repository.redhat.com/ga/com/redhat/amq-broker/artemis-prometheus-metrics-plugin/
https://maven.repository.redhat.com/ga/com/redhat/amq-broker/artemis-prometheus-metrics-plugin-servlet/

The artifact 2.1.0 will be published the next week.
